//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAT.ConnectedServices.OkapiService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.okapi.tm.com", ConfigurationName="OkapiService.IOkapiService")]
    public interface IOkapiService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OkapiService.getStatisticsForDocumentResponse> getStatisticsForDocumentAsync(OkapiService.getStatisticsForDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OkapiService.createXliffResponse> createXliffAsync(OkapiService.createXliffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tmExistsReturn")]
        System.Threading.Tasks.Task<bool> tmExistsAsync(string sTMName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createTMReturn")]
        System.Threading.Tasks.Task<bool> createTMAsync(string sTMName, string sSourceLangIso639_1, string sTargetLangIso639_1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OkapiService.getTMMatchesResponse> getTMMatchesAsync(OkapiService.getTMMatchesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task deleteTMEntryAsync(string sTMName, int idEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task updateTMEntryAsync(string sTMName, int idEntry, string jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="exportTMXReturn")]
        System.Threading.Tasks.Task<string> exportTMXAsync(string sTMName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OkapiService.concordanceResponse> concordanceAsync(OkapiService.concordanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OkapiService.preTranslateXliffResponse> preTranslateXliffAsync(OkapiService.preTranslateXliffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTMInfoReturn")]
        System.Threading.Tasks.Task<OkapiService.TMInfo> getTMInfoAsync(string sTMName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="importTMXReturn")]
        System.Threading.Tasks.Task<OkapiService.TMImportResult> importTMXAsync(string sTMName, string sTmxContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTMLastUpdatedReturn")]
        System.Threading.Tasks.Task<System.DateTime> getTMLastUpdatedAsync(string sTMName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OkapiService.addTMEntriesResponse> addTMEntriesAsync(OkapiService.addTMEntriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OkapiService.getTMListResponse> getTMListAsync(OkapiService.getTMListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRepositoryInfoReturn")]
        System.Threading.Tasks.Task<OkapiService.RepositoryInfo> getRepositoryInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task setTMEntryCustomFieldAsync(string sTMName, int key, string fieldName, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OkapiService.createDocumentFromXliffResponse> createDocumentFromXliffAsync(OkapiService.createDocumentFromXliffRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.okapi.tm.com")]
    public partial class TMAssignment
    {
        
        private string tMNameField;
        
        private int penaltyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TMName
        {
            get
            {
                return this.tMNameField;
            }
            set
            {
                this.tMNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int penalty
        {
            get
            {
                return this.penaltyField;
            }
            set
            {
                this.penaltyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.okapi.tm.com")]
    public partial class RepositoryInfo
    {
        
        private long sizeField;
        
        private long filesField;
        
        private System.Nullable<System.DateTime> lastSaveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> lastSave
        {
            get
            {
                return this.lastSaveField;
            }
            set
            {
                this.lastSaveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.okapi.tm.com")]
    public partial class TMEntry
    {
        
        private string idField;
        
        private string sourceField;
        
        private string targetField;
        
        private string metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.okapi.tm.com")]
    public partial class TMImportResult
    {
        
        private int allItemsField;
        
        private int importedItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int allItems
        {
            get
            {
                return this.allItemsField;
            }
            set
            {
                this.allItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int importedItems
        {
            get
            {
                return this.importedItemsField;
            }
            set
            {
                this.importedItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.okapi.tm.com")]
    public partial class TMInfo
    {
        
        private string langFromField;
        
        private string langToField;
        
        private string nameField;
        
        private string guidField;
        
        private int entryNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string langFrom
        {
            get
            {
                return this.langFromField;
            }
            set
            {
                this.langFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string langTo
        {
            get
            {
                return this.langToField;
            }
            set
            {
                this.langToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int entryNumber
        {
            get
            {
                return this.entryNumberField;
            }
            set
            {
                this.entryNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.okapi.tm.com")]
    public partial class CorpusEntry
    {
        
        private int idField;
        
        private string guidField;
        
        private string sourceField;
        
        private string targetField;
        
        private string metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.okapi.tm.com")]
    public partial class TMMatch
    {
        
        private string idField;
        
        private string sourceField;
        
        private string targetField;
        
        private string originField;
        
        private int qualityField;
        
        private string metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quality
        {
            get
            {
                return this.qualityField;
            }
            set
            {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.okapi.tm.com")]
    public partial class Statistics
    {
        
        private string sourceLangField;
        
        private string targetLangField;
        
        private int repetitionField;
        
        private int match_100Field;
        
        private int match_101Field;
        
        private int match_50_74Field;
        
        private int match_75_84Field;
        
        private int match_85_94Field;
        
        private int match_95_99Field;
        
        private int no_matchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sourceLang
        {
            get
            {
                return this.sourceLangField;
            }
            set
            {
                this.sourceLangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string targetLang
        {
            get
            {
                return this.targetLangField;
            }
            set
            {
                this.targetLangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int repetition
        {
            get
            {
                return this.repetitionField;
            }
            set
            {
                this.repetitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int match_100
        {
            get
            {
                return this.match_100Field;
            }
            set
            {
                this.match_100Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int match_101
        {
            get
            {
                return this.match_101Field;
            }
            set
            {
                this.match_101Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int match_50_74
        {
            get
            {
                return this.match_50_74Field;
            }
            set
            {
                this.match_50_74Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int match_75_84
        {
            get
            {
                return this.match_75_84Field;
            }
            set
            {
                this.match_75_84Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int match_85_94
        {
            get
            {
                return this.match_85_94Field;
            }
            set
            {
                this.match_85_94Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int match_95_99
        {
            get
            {
                return this.match_95_99Field;
            }
            set
            {
                this.match_95_99Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int no_match
        {
            get
            {
                return this.no_matchField;
            }
            set
            {
                this.no_matchField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatisticsForDocument", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class getStatisticsForDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public string sFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=2)]
        public string sFilterName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] filterContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=4)]
        public string sourceLangISO639_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("aTargetLangsISO639_1")]
        public string[] aTargetLangsISO639_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("aTMAssignments")]
        public OkapiService.TMAssignment[] aTMAssignments;
        
        public getStatisticsForDocumentRequest()
        {
        }
        
        public getStatisticsForDocumentRequest(string sFileName, byte[] fileContent, string sFilterName, byte[] filterContent, string sourceLangISO639_1, string[] aTargetLangsISO639_1, OkapiService.TMAssignment[] aTMAssignments)
        {
            this.sFileName = sFileName;
            this.fileContent = fileContent;
            this.sFilterName = sFilterName;
            this.filterContent = filterContent;
            this.sourceLangISO639_1 = sourceLangISO639_1;
            this.aTargetLangsISO639_1 = aTargetLangsISO639_1;
            this.aTMAssignments = aTMAssignments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatisticsForDocumentResponse", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class getStatisticsForDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getStatisticsForDocumentReturn")]
        public OkapiService.Statistics[] getStatisticsForDocumentReturn;
        
        public getStatisticsForDocumentResponse()
        {
        }
        
        public getStatisticsForDocumentResponse(OkapiService.Statistics[] getStatisticsForDocumentReturn)
        {
            this.getStatisticsForDocumentReturn = getStatisticsForDocumentReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createXliff", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class createXliffRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public string sFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=2)]
        public string sFilterName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] filterContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=4)]
        public string sourceLangISO639_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=5)]
        public string targetLangISO639_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("aTMAssignments")]
        public OkapiService.TMAssignment[] aTMAssignments;
        
        public createXliffRequest()
        {
        }
        
        public createXliffRequest(string sFileName, byte[] fileContent, string sFilterName, byte[] filterContent, string sourceLangISO639_1, string targetLangISO639_1, OkapiService.TMAssignment[] aTMAssignments)
        {
            this.sFileName = sFileName;
            this.fileContent = fileContent;
            this.sFilterName = sFilterName;
            this.filterContent = filterContent;
            this.sourceLangISO639_1 = sourceLangISO639_1;
            this.targetLangISO639_1 = targetLangISO639_1;
            this.aTMAssignments = aTMAssignments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createXliffResponse", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class createXliffResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public string createXliffReturn;
        
        public createXliffResponse()
        {
        }
        
        public createXliffResponse(string createXliffReturn)
        {
            this.createXliffReturn = createXliffReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTMMatches", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class getTMMatchesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("aTMNames")]
        public string[] aTMNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=1)]
        public string sSourceText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=2)]
        public string sPrevText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=3)]
        public string sNextText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=4)]
        public sbyte matchThreshold;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=5)]
        public int maxHits;
        
        public getTMMatchesRequest()
        {
        }
        
        public getTMMatchesRequest(string[] aTMNames, string sSourceText, string sPrevText, string sNextText, sbyte matchThreshold, int maxHits)
        {
            this.aTMNames = aTMNames;
            this.sSourceText = sSourceText;
            this.sPrevText = sPrevText;
            this.sNextText = sNextText;
            this.matchThreshold = matchThreshold;
            this.maxHits = maxHits;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTMMatchesResponse", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class getTMMatchesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getTMMatchesReturn")]
        public OkapiService.TMMatch[] getTMMatchesReturn;
        
        public getTMMatchesResponse()
        {
        }
        
        public getTMMatchesResponse(OkapiService.TMMatch[] getTMMatchesReturn)
        {
            this.getTMMatchesReturn = getTMMatchesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="concordance", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class concordanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("aTMNames")]
        public string[] aTMNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=1)]
        public string sSourceText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=2)]
        public string sTargetText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=3)]
        public bool bCaseSensitive;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=4)]
        public bool bNumericEquivalenve;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=5)]
        public int nLimit;
        
        public concordanceRequest()
        {
        }
        
        public concordanceRequest(string[] aTMNames, string sSourceText, string sTargetText, bool bCaseSensitive, bool bNumericEquivalenve, int nLimit)
        {
            this.aTMNames = aTMNames;
            this.sSourceText = sSourceText;
            this.sTargetText = sTargetText;
            this.bCaseSensitive = bCaseSensitive;
            this.bNumericEquivalenve = bNumericEquivalenve;
            this.nLimit = nLimit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="concordanceResponse", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class concordanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("concordanceReturn")]
        public OkapiService.CorpusEntry[] concordanceReturn;
        
        public concordanceResponse()
        {
        }
        
        public concordanceResponse(OkapiService.CorpusEntry[] concordanceReturn)
        {
            this.concordanceReturn = concordanceReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="preTranslateXliff", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class preTranslateXliffRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public string sXliffContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=1)]
        public string sourceLangISO639_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=2)]
        public string targetLangISO639_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("aTMAssignments")]
        public OkapiService.TMAssignment[] aTMAssignments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=4)]
        public int matchThreshold;
        
        public preTranslateXliffRequest()
        {
        }
        
        public preTranslateXliffRequest(string sXliffContent, string sourceLangISO639_1, string targetLangISO639_1, OkapiService.TMAssignment[] aTMAssignments, int matchThreshold)
        {
            this.sXliffContent = sXliffContent;
            this.sourceLangISO639_1 = sourceLangISO639_1;
            this.targetLangISO639_1 = targetLangISO639_1;
            this.aTMAssignments = aTMAssignments;
            this.matchThreshold = matchThreshold;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="preTranslateXliffResponse", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class preTranslateXliffResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public string preTranslateXliffReturn;
        
        public preTranslateXliffResponse()
        {
        }
        
        public preTranslateXliffResponse(string preTranslateXliffReturn)
        {
            this.preTranslateXliffReturn = preTranslateXliffReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addTMEntries", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class addTMEntriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public string sTMName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("tmEntries")]
        public OkapiService.TMEntry[] tmEntries;
        
        public addTMEntriesRequest()
        {
        }
        
        public addTMEntriesRequest(string sTMName, OkapiService.TMEntry[] tmEntries)
        {
            this.sTMName = sTMName;
            this.tmEntries = tmEntries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addTMEntriesResponse", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class addTMEntriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public int addTMEntriesReturn;
        
        public addTMEntriesResponse()
        {
        }
        
        public addTMEntriesResponse(int addTMEntriesReturn)
        {
            this.addTMEntriesReturn = addTMEntriesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTMList", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class getTMListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public string sTMNameContains;
        
        public getTMListRequest()
        {
        }
        
        public getTMListRequest(string sTMNameContains)
        {
            this.sTMNameContains = sTMNameContains;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTMListResponse", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class getTMListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getTMListReturn")]
        public OkapiService.TMInfo[] getTMListReturn;
        
        public getTMListResponse()
        {
        }
        
        public getTMListResponse(OkapiService.TMInfo[] getTMListReturn)
        {
            this.getTMListReturn = getTMListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDocumentFromXliff", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class createDocumentFromXliffRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        public string sFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=2)]
        public string sFilterName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] filterContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=4)]
        public string sourceLangISO639_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=5)]
        public string targetLangISO639_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=6)]
        public string sXliffContent;
        
        public createDocumentFromXliffRequest()
        {
        }
        
        public createDocumentFromXliffRequest(string sFileName, byte[] fileContent, string sFilterName, byte[] filterContent, string sourceLangISO639_1, string targetLangISO639_1, string sXliffContent)
        {
            this.sFileName = sFileName;
            this.fileContent = fileContent;
            this.sFilterName = sFilterName;
            this.filterContent = filterContent;
            this.sourceLangISO639_1 = sourceLangISO639_1;
            this.targetLangISO639_1 = targetLangISO639_1;
            this.sXliffContent = sXliffContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDocumentFromXliffResponse", WrapperNamespace="http://service.okapi.tm.com", IsWrapped=true)]
    public partial class createDocumentFromXliffResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.okapi.tm.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] createDocumentFromXliffReturn;
        
        public createDocumentFromXliffResponse()
        {
        }
        
        public createDocumentFromXliffResponse(byte[] createDocumentFromXliffReturn)
        {
            this.createDocumentFromXliffReturn = createDocumentFromXliffReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface OkapiServiceChannel : OkapiService.IOkapiService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class OkapiServiceClient : System.ServiceModel.ClientBase<OkapiService.IOkapiService>, OkapiService.IOkapiService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OkapiServiceClient() : 
                base(OkapiServiceClient.GetDefaultBinding(), OkapiServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OkapiService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OkapiServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OkapiServiceClient.GetBindingForEndpoint(endpointConfiguration), OkapiServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OkapiServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OkapiServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OkapiServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OkapiServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OkapiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OkapiService.getStatisticsForDocumentResponse> OkapiService.IOkapiService.getStatisticsForDocumentAsync(OkapiService.getStatisticsForDocumentRequest request)
        {
            return base.Channel.getStatisticsForDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<OkapiService.getStatisticsForDocumentResponse> getStatisticsForDocumentAsync(string sFileName, byte[] fileContent, string sFilterName, byte[] filterContent, string sourceLangISO639_1, string[] aTargetLangsISO639_1, OkapiService.TMAssignment[] aTMAssignments)
        {
            OkapiService.getStatisticsForDocumentRequest inValue = new OkapiService.getStatisticsForDocumentRequest();
            inValue.sFileName = sFileName;
            inValue.fileContent = fileContent;
            inValue.sFilterName = sFilterName;
            inValue.filterContent = filterContent;
            inValue.sourceLangISO639_1 = sourceLangISO639_1;
            inValue.aTargetLangsISO639_1 = aTargetLangsISO639_1;
            inValue.aTMAssignments = aTMAssignments;
            return ((OkapiService.IOkapiService)(this)).getStatisticsForDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OkapiService.createXliffResponse> OkapiService.IOkapiService.createXliffAsync(OkapiService.createXliffRequest request)
        {
            return base.Channel.createXliffAsync(request);
        }
        
        public System.Threading.Tasks.Task<OkapiService.createXliffResponse> createXliffAsync(string sFileName, byte[] fileContent, string sFilterName, byte[] filterContent, string sourceLangISO639_1, string targetLangISO639_1, OkapiService.TMAssignment[] aTMAssignments)
        {
            OkapiService.createXliffRequest inValue = new OkapiService.createXliffRequest();
            inValue.sFileName = sFileName;
            inValue.fileContent = fileContent;
            inValue.sFilterName = sFilterName;
            inValue.filterContent = filterContent;
            inValue.sourceLangISO639_1 = sourceLangISO639_1;
            inValue.targetLangISO639_1 = targetLangISO639_1;
            inValue.aTMAssignments = aTMAssignments;
            return ((OkapiService.IOkapiService)(this)).createXliffAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> tmExistsAsync(string sTMName)
        {
            return base.Channel.tmExistsAsync(sTMName);
        }
        
        public System.Threading.Tasks.Task<bool> createTMAsync(string sTMName, string sSourceLangIso639_1, string sTargetLangIso639_1)
        {
            return base.Channel.createTMAsync(sTMName, sSourceLangIso639_1, sTargetLangIso639_1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OkapiService.getTMMatchesResponse> OkapiService.IOkapiService.getTMMatchesAsync(OkapiService.getTMMatchesRequest request)
        {
            return base.Channel.getTMMatchesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OkapiService.getTMMatchesResponse> getTMMatchesAsync(string[] aTMNames, string sSourceText, string sPrevText, string sNextText, sbyte matchThreshold, int maxHits)
        {
            OkapiService.getTMMatchesRequest inValue = new OkapiService.getTMMatchesRequest();
            inValue.aTMNames = aTMNames;
            inValue.sSourceText = sSourceText;
            inValue.sPrevText = sPrevText;
            inValue.sNextText = sNextText;
            inValue.matchThreshold = matchThreshold;
            inValue.maxHits = maxHits;
            return ((OkapiService.IOkapiService)(this)).getTMMatchesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task deleteTMEntryAsync(string sTMName, int idEntry)
        {
            return base.Channel.deleteTMEntryAsync(sTMName, idEntry);
        }
        
        public System.Threading.Tasks.Task updateTMEntryAsync(string sTMName, int idEntry, string jsonData)
        {
            return base.Channel.updateTMEntryAsync(sTMName, idEntry, jsonData);
        }
        
        public System.Threading.Tasks.Task<string> exportTMXAsync(string sTMName)
        {
            return base.Channel.exportTMXAsync(sTMName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OkapiService.concordanceResponse> OkapiService.IOkapiService.concordanceAsync(OkapiService.concordanceRequest request)
        {
            return base.Channel.concordanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<OkapiService.concordanceResponse> concordanceAsync(string[] aTMNames, string sSourceText, string sTargetText, bool bCaseSensitive, bool bNumericEquivalenve, int nLimit)
        {
            OkapiService.concordanceRequest inValue = new OkapiService.concordanceRequest();
            inValue.aTMNames = aTMNames;
            inValue.sSourceText = sSourceText;
            inValue.sTargetText = sTargetText;
            inValue.bCaseSensitive = bCaseSensitive;
            inValue.bNumericEquivalenve = bNumericEquivalenve;
            inValue.nLimit = nLimit;
            return ((OkapiService.IOkapiService)(this)).concordanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OkapiService.preTranslateXliffResponse> OkapiService.IOkapiService.preTranslateXliffAsync(OkapiService.preTranslateXliffRequest request)
        {
            return base.Channel.preTranslateXliffAsync(request);
        }
        
        public System.Threading.Tasks.Task<OkapiService.preTranslateXliffResponse> preTranslateXliffAsync(string sXliffContent, string sourceLangISO639_1, string targetLangISO639_1, OkapiService.TMAssignment[] aTMAssignments, int matchThreshold)
        {
            OkapiService.preTranslateXliffRequest inValue = new OkapiService.preTranslateXliffRequest();
            inValue.sXliffContent = sXliffContent;
            inValue.sourceLangISO639_1 = sourceLangISO639_1;
            inValue.targetLangISO639_1 = targetLangISO639_1;
            inValue.aTMAssignments = aTMAssignments;
            inValue.matchThreshold = matchThreshold;
            return ((OkapiService.IOkapiService)(this)).preTranslateXliffAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<OkapiService.TMInfo> getTMInfoAsync(string sTMName)
        {
            return base.Channel.getTMInfoAsync(sTMName);
        }
        
        public System.Threading.Tasks.Task<OkapiService.TMImportResult> importTMXAsync(string sTMName, string sTmxContent)
        {
            return base.Channel.importTMXAsync(sTMName, sTmxContent);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getTMLastUpdatedAsync(string sTMName)
        {
            return base.Channel.getTMLastUpdatedAsync(sTMName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OkapiService.addTMEntriesResponse> OkapiService.IOkapiService.addTMEntriesAsync(OkapiService.addTMEntriesRequest request)
        {
            return base.Channel.addTMEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OkapiService.addTMEntriesResponse> addTMEntriesAsync(string sTMName, OkapiService.TMEntry[] tmEntries)
        {
            OkapiService.addTMEntriesRequest inValue = new OkapiService.addTMEntriesRequest();
            inValue.sTMName = sTMName;
            inValue.tmEntries = tmEntries;
            return ((OkapiService.IOkapiService)(this)).addTMEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OkapiService.getTMListResponse> OkapiService.IOkapiService.getTMListAsync(OkapiService.getTMListRequest request)
        {
            return base.Channel.getTMListAsync(request);
        }
        
        public System.Threading.Tasks.Task<OkapiService.getTMListResponse> getTMListAsync(string sTMNameContains)
        {
            OkapiService.getTMListRequest inValue = new OkapiService.getTMListRequest();
            inValue.sTMNameContains = sTMNameContains;
            return ((OkapiService.IOkapiService)(this)).getTMListAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<OkapiService.RepositoryInfo> getRepositoryInfoAsync()
        {
            return base.Channel.getRepositoryInfoAsync();
        }
        
        public System.Threading.Tasks.Task setTMEntryCustomFieldAsync(string sTMName, int key, string fieldName, string value)
        {
            return base.Channel.setTMEntryCustomFieldAsync(sTMName, key, fieldName, value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OkapiService.createDocumentFromXliffResponse> OkapiService.IOkapiService.createDocumentFromXliffAsync(OkapiService.createDocumentFromXliffRequest request)
        {
            return base.Channel.createDocumentFromXliffAsync(request);
        }
        
        public System.Threading.Tasks.Task<OkapiService.createDocumentFromXliffResponse> createDocumentFromXliffAsync(string sFileName, byte[] fileContent, string sFilterName, byte[] filterContent, string sourceLangISO639_1, string targetLangISO639_1, string sXliffContent)
        {
            OkapiService.createDocumentFromXliffRequest inValue = new OkapiService.createDocumentFromXliffRequest();
            inValue.sFileName = sFileName;
            inValue.fileContent = fileContent;
            inValue.sFilterName = sFilterName;
            inValue.filterContent = filterContent;
            inValue.sourceLangISO639_1 = sourceLangISO639_1;
            inValue.targetLangISO639_1 = targetLangISO639_1;
            inValue.sXliffContent = sXliffContent;
            return ((OkapiService.IOkapiService)(this)).createDocumentFromXliffAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OkapiService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OkapiService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.20.55:8080/OkapiService/services/OkapiService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OkapiServiceClient.GetBindingForEndpoint(EndpointConfiguration.OkapiService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OkapiServiceClient.GetEndpointAddress(EndpointConfiguration.OkapiService);
        }
        
        public enum EndpointConfiguration
        {
            
            OkapiService,
        }
    }
}
