// <auto-generated />
using System;
using CAT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAT.Migrations.TranslationUnits
{
    [DbContext(typeof(TranslationUnitsDbContext))]
    [Migration("20231118200617_TranslationUnitsUpdate")]
    partial class TranslationUnitsUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CAT.Models.Entities.TranslationUnits.TranslationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("context")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("documentId")
                        .HasColumnType("int");

                    b.Property<int>("locks")
                        .HasColumnType("int");

                    b.Property<string>("source")
                        .HasColumnType("longtext");

                    b.Property<long>("status")
                        .HasColumnType("bigint");

                    b.Property<string>("target")
                        .HasColumnType("longtext");

                    b.Property<int>("tuid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("documentId");

                    b.ToTable("TranslationUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
