apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-main
  template:
    metadata:
      labels:
        app: cat-main
    spec:
      containers:
        - name: cat-main
          image: registry.digitalocean.com/languageops/cat-main
          volumeMounts:
            - name: cat-data-claim
              mountPath: /data  # Mount path inside the container
      volumes:
        - name: cat-data-claim
          persistentVolumeClaim:
            claimName: cat-data-claim  # Name of the PVC
