apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cat-csi-app-set
spec:
  selector:
    matchLabels:
      app: catpod
  serviceName: "cat-frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: catpod
    spec:
      containers:
      - name: cat-frontend
        image: busybox
        args:
        - sleep
        - infinity
        volumeMounts:
        - mountPath: "/data"
          name: csi-pvc
  volumeClaimTemplates:
  - metadata:
      name: csi-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage 
 
 
 
 
