apiVersion: v1
kind: Service
metadata:
  name: samba-service
spec:
  selector:
    app: samba
  ports:
    - name: port-139
      protocol: TCP
      port: 139
      targetPort: 139
    - name: port-445
      protocol: TCP
      port: 445
      targetPort: 445
  type: LoadBalancer
