apiVersion: v1
kind: Service
metadata:
  name: samba-service
spec:
  type: LoadBalancer
  selector:
    app: ubuntu-pod  # Match the label of your Ubuntu Pod
  ports:
    - protocol: TCP
      port: 445      # The Samba port (adjust as needed)
      targetPort: 445
